services:
  db:
    image: postgres:17
    restart: unless-stopped
    networks:
      - default
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    command:
    - "start-dev"
    - "--proxy-headers"
    - "xforwarded"
    - "--spi-connections-http-client-default-disable-trust-manager=true"
    restart: unless-stopped
    networks:
      - default
      - frontend
    environment:
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_SCHEMA=public
      - KC_HOSTNAME=scim-idp.openproject-edge.com
      - KC_TRANSACTION_XA_ENABLED=false
    volumes:
      - keycloak-data:/opt/keycloak/data/
      - ./themes/:/opt/keycloak/themes/
      - ./providers/:/opt/keycloak/providers/
    depends_on:
      - db

volumes:
  keycloak-data:
  pgdata:

networks:
  frontend:
    name: frontend
    external: true
